buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.+'
    }
}
        
apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'eclipse'
apply plugin: 'maven-publish'

version = '1.0.3'
group = 'com.Nyonio.mekanism_advanced_configuration_card'
archivesBaseName = 'mekanism_advanced_configuration_card-1.12.2'

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8'

minecraft {
    mappings channel: 'snapshot', version: '20171003-1.12'
    
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
        }

        server {
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
        }
    }
}

repositories {
    maven { url = 'https://maven.minecraftforge.net/' }
    mavenCentral()
    maven { url = 'https://maven.cil.li/' }
    maven { url = 'https://cursemaven.com/' }
    maven { url = 'https://repo.spongepowered.org/maven/' }
    maven { url = 'https://modmaven.k-4u.nl/' }
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2859'
    
    compile files('libs/Mekanism-CE-1.12.2-deobf.jar')
    compileOnly files('libs/Baubles-1.12-1.5.2.jar')
    compileOnly files('libs/InventoryTweaks-1.63.jar')
    compileOnly files('libs/ae2-uel-v0.56.6.jar')
    compileOnly files('libs/jei_1.12.2-4.16.1.1013.jar')
    compile 'curse.maven:redstone-flux-270789:2920436'
    compile 'curse.maven:industrial-craft-242638:3838713'
    compileOnly files('libs/!mixinbooter-10.7.jar')
}

jar {
    manifest {
        attributes([
            "Specification-Title": "mekanism_advanced_configuration_card",
            "Specification-Vendor": "Nyonio",
            "Specification-Version": "1",
            "Implementation-Title": project.name,
            "Implementation-Version": "${version}",
            "Implementation-Vendor" :"Nyonio",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
            "MixinConfigs": "mixins.mekanism_advanced_configuration_card.json"
        ])
    }
}

task copyToMods(type: Copy, dependsOn: jar) {
    from jar.archivePath
    into 'D:/pcl2/.minecraft/versions/1.12.2-Forge_14.23.5.2864/mods'
}

build.finalizedBy copyToMods 

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}
